# Generated by Django 3.2.5 on 2021-07-20 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(error_messages={'max_length': 'O máximo de caracteres que um titulo pode ter são 30!'}, help_text='Coloque o título do vídeo', max_length=30, validators=[django.core.validators.MaxLengthValidator])),
                ('descricao', models.CharField(error_messages={'max_length': 'O máximo de caracteres que uma descrição pode ter são 300!'}, help_text='Coloque a descrição do vídeo', max_length=300, validators=[django.core.validators.MaxLengthValidator])),
                ('url', models.CharField(error_messages={'max_length': 'O máximo de caracteres que uma url pode ter são 200!'}, help_text='Coloque o link para o vídeo', max_length=200, validators=[django.core.validators.URLValidator, django.core.validators.MaxLengthValidator])),
            ],
        ),
    ]
