# Generated by Django 3.2.5 on 2021-08-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obeflix_back', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoriaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='obeflix_back.categoria'),
        ),
    ]
