# Generated by Django 3.2.5 on 2021-07-20 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeflix_back', '0002_auto_20210720_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.CharField(error_messages={'max_length': 'O máximo de caracteres que uma descrição pode ter são 300!'}, help_text='Coloque a descrição do vídeo', max_length=300, validators=[django.core.validators.MaxLengthValidator]),
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(error_messages={'max_length': 'O máximo de caracteres que um titulo pode ter são 30!'}, help_text='Coloque o título do vídeo', max_length=30, validators=[django.core.validators.MaxLengthValidator]),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(error_messages={'max_length': 'O máximo de caracteres que uma url pode ter são 200!'}, help_text='Coloque o link para o vídeo', validators=[django.core.validators.URLValidator, django.core.validators.MaxLengthValidator]),
        ),
    ]
