# Generated by Django 3.2.5 on 2021-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeflix_back', '0003_auto_20210720_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(error_messages={'max_length': 'O máximo de caracteres que uma url pode ter são 200!'}, help_text='Coloque o link para o vídeo'),
        ),
    ]
