# Generated by Django 3.2.5 on 2021-07-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeflix_back', '0007_auto_20210720_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.CharField(help_text='Coloque a descrição do vídeo', max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(help_text='Coloque o título do vídeo', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='Coloque o link para o vídeo'),
        ),
    ]
